GET localhost:8080/account

###

PUT localhost:8080/account/credit/balance
Content-Type: application/json

{
"balance": 20.0
}

###

POST localhost:8080/transaction
Content-Type: application/json

{
"amount": 200,
  "mode": "credit"
}

###
GET localhost:8080/transaction/id
